[package]
name = "turbo-composeer-schemas"
version = "0.1.0"
edition = "2024"


[build-dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
schemars = "0.8"
typify = "0.4.0"
syn = "2"
serde = { version = "1" }
serde_json = "1"
